# .streamlit/config.toml
[theme]
base = "dark"  # This forces Dark Mode as the default
primaryColor = "#007bff"
backgroundColor = "#0e1117"
secondaryBackgroundColor = "#262730"
textColor = "#fafafa"
font = "sans serif"